### ISSUE TITLE
GAMMA error with ARG-ANNOT database

### ISSUE THREAD

**Issue by kapsakcj** [rastanton/GAMMA#6]
Hi Rich,

I tried using the ARG-ANNOT database that you have linked in the README and encountered an error when using with GAMMA:
```
$ wget http://backup.mediterranee-infection.com/arkotheque/client/ihumed/_depot_arko/articles/2041/arg-annot-v4-aa-may2018_doc.fasta
--2021-12-29 16:43:37--  http://backup.mediterranee-infection.com/arkotheque/client/ihumed/_depot_arko/articles/2041/arg-annot-v4-aa-may2018_doc.fasta
Resolving backup.mediterranee-infection.com (backup.mediterranee-infection.com)... 213.186.33.40
Connecting to backup.mediterranee-infection.com (backup.mediterranee-infection.com)|213.186.33.40|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 691109 (675K)
Saving to: 'arg-annot-v4-aa-may2018_doc.fasta'

arg-annot-v4-aa-may2018_doc.fast 100%[==========================================================>] 674.91K  1.48MB/s    in 0.4s

2021-12-29 16:43:38 (1.48 MB/s) - 'arg-annot-v4-aa-may2018_doc.fasta' saved [691109/691109]


# testing with a Salmonella assembly
$ GAMMA.py GCA_011245895.1_PDT000672941.1_genomic.fna arg-annot-v4-aa-may2018_doc.fasta output.gamma.arganot.tsv
Loaded 604334 letters in 2038 sequences
Error: sequence name (Tet)Tet(48):NG_055773:1-1200:1200 is repeated in the database, all names must be unique.
Traceback (most recent call last):
  File "/GAMMA/GAMMA.py", line 1033, in <module>
    sys.exit(main())
  File "/GAMMA/GAMMA.py", line 1026, in main
    GAMMA_Out(args.input_fasta, args.database, args.output,  args.percent_identity, Verbose)
  File "/GAMMA/GAMMA.py", line 1001, in GAMMA_Out
    GAMA_Output(output +'.psl', fasta, gene_db, output + '.gamma', verbose)
  File "/GAMMA/GAMMA.py", line 929, in GAMA_Output
    List1 = GAMA_List(PSL, genome_fasta, genes_fasta, verbose)
  File "/GAMMA/GAMMA.py", line 919, in GAMA_List
    Lines = GAMA_Line_Maker(PSL, genome_fasta, genes_fasta, verbose)
  File "/GAMMA/GAMMA.py", line 728, in GAMA_Line_Maker
    Genes = SeqIO.to_dict(SeqIO.parse(genes_fasta, 'fasta'))
  File "/usr/local/lib/python3.6/dist-packages/Bio/SeqIO/__init__.py", line 737, in to_dict
    raise ValueError("Duplicate key '%s'" % key)
ValueError: Duplicate key '(Tet)Tet(48):NG_055773:1-1200:1200'
```

I'm running GAMMA via a docker image: https://hub.docker.com/r/staphb/gamma/tags
Dockerfile: https://github.com/StaPH-B/docker-builds/blob/master/gamma/1.4/Dockerfile

Install is non-standard but I was able to run GAMMA successfully with ResFinder and NCBI amrfinderplus databases so this leads me to believe the issue is specific to the arg-annot db.

Curtis

**Comment by rastanton** [comment]
Hi Curtis,

That database doesn't work because there are multiple entries with the
exact same name, which causes that error.

That database wouldn't actually work anyways because it's for protein
sequences, so it looks like I linked to the wrong version of ARG-ANNOT.
This one should be used instead, I will update the git readme to reflect
this change:

http://backup.mediterranee-infection.com/arkotheque/client/ihumed/_depot_arko/articles/691/argannot-nt_doc.fasta

Thanks--Rich

**Comment by kapsakcj** [comment]
Thanks for the quick reply & fix Rich. That new link & database solved the issue!

Happy (almost) New Year!
